insert into addresses (`name`)
values ('24402 Warner Place'),
       ('4 La Follette Plaza'),
       ('700 Monterey Avenue'),
       ('93124 Comanche Way'),
       ('57659 Karstens Junction'),
       ('361 Caliangt Court'),
       ('88941 Starling Drive'),
       ('34 Briar Crest Crossing'),
       ('2 Cascade Lane'),
       ('40 Havey Road'),
       ('67636 Tennessee Point'),
       ('385 Rieder Center'),
       ('32975 Hagan Street'),
       ('86462 Buena Vista Point'),
       ('1275 Pine View Court'),
       ('4673 Colorado Road'),
       ('6 Hanover Terrace'),
       ('66 Thompson Drive'),
       ('4 Haas Lane'),
       ('8 Warner Drive'),
       ('48738 Thompson Lane'),
       ('0590 Lawn Hill'),
       ('68 Roxbury Court'),
       ('833 Kenwood Plaza'),
       ('6 Sachs Way'),
       ('77485 Commercial Drive'),
       ('80678 Green Ridge Court'),
       ('84320 Lotheville Way'),
       ('2 Del Mar Park'),
       ('04528 Carpenter Plaza'),
       ('9590 Briar Crest Street'),
       ('02335 Vernon Avenue'),
       ('6638 Thompson Point'),
       ('0 Mariners Cove Circle'),
       ('897 Pine View Park'),
       ('835 Calypso Place'),
       ('904 Karstens Trail'),
       ('52 Corben Pass'),
       ('27803 Morningstar Avenue'),
       ('214 Esker Trail'),
       ('17 Huxley Pass'),
       ('2061 Meadow Vale Point'),
       ('02 Browning Parkway'),
       ('54 3rd Pass'),
       ('5 Truax Court'),
       ('59402 Kim Court'),
       ('59 Atwood Alley'),
       ('55759 Valley Edge Pass'),
       ('35 Kim Road'),
       ('79 Gina Way');


insert into categories (`name`)
values ('Hatchback'),
       ('Coupe'),
       ('Cabrio'),
       ('Sedan'),
       ('SUV');