insert into addresses (`name`)
values ('6422 Kenwood Street'),
       ('263 Glendale Lane'),
       ('781 Luster Junction'),
       ('1 Express Parkway'),
       ('42 Eggendart Trail'),
       ('3569 Canary Lane'),
       ('713 Brown Point'),
       ('253 Carpenter Plaza'),
       ('78859 Mifflin Place'),
       ('0 Arkansas Center'),
       ('8868 Arkansas Parkway'),
       ('29 Dunning Avenue'),
       ('5 New Castle Terrace'),
       ('411 Pankratz Court'),
       ('75 Harper Way'),
       ('118 Nelson Plaza'),
       ('42 Del Sol Court'),
       ('80315 Sherman Lane'),
       ('2 Bluejay Parkway'),
       ('33901 Pond Circle'),
       ('3 Homewood Circle'),
       ('6776 Village Green Court'),
       ('8 Kinsman Avenue'),
       ('575 Homewood Alley'),
       ('0938 Vermont Junction'),
       ('03632 Carey Trail'),
       ('0922 Stang Circle'),
       ('1930 Quincy Trail'),
       ('432 Elka Hill'),
       ('2 Spaight Alley'),
       ('4442 Heffernan Drive'),
       ('53533 Novick Pass'),
       ('50 Mesta Road'),
       ('90 Summer Ridge Lane'),
       ('241 Burning Wood Plaza'),
       ('6507 Burrows Way'),
       ('5 8th Avenue'),
       ('2 Brown Drive'),
       ('92 Memorial Park'),
       ('036 Stuart Pass'),
       ('13 Maryland Road'),
       ('10 Jenna Park'),
       ('33097 Rieder Pass'),
       ('31314 Butterfield Lane'),
       ('78 Hollow Ridge Junction'),
       ('008 Heffernan Center'),
       ('9 Marcy Court'),
       ('121 Miller Junction'),
       ('906 Buhler Hill'),
       ('6 Evergreen Way'),
       ('86530 Dovetail Park'),
       ('31 Bartillon Way'),
       ('88229 Norway Maple Court'),
       ('5 Sunbrook Point'),
       ('5667 Brentwood Alley'),
       ('887 Rieder Way'),
       ('9324 Shopko Alley'),
       ('699 Alpine Alley'),
       ('29 Beilfuss Center'),
       ('801 Brickson Park Avenue'),
       ('811 Maywood Parkway'),
       ('415 2nd Center'),
       ('46688 Sherman Park'),
       ('60044 Bayside Pass'),
       ('43 Schurz Park'),
       ('20605 Helena Lane'),
       ('9 Mesta Lane'),
       ('5 Homewood Trail'),
       ('33 Prentice Junction'),
       ('51 Algoma Crossing'),
       ('22058 Northland Trail'),
       ('6751 Village Place'),
       ('67 Twin Pines Center'),
       ('1 School Court'),
       ('3696 Elmside Lane'),
       ('22 Riverside Drive'),
       ('1018 Manufacturers Court'),
       ('937 Montana Plaza'),
       ('266 Dayton Street'),
       ('1 West Center'),
       ('8887 Artisan Pass'),
       ('9131 Everett Alley'),
       ('1 Nancy Trail'),
       ('04 La Follette Pass'),
       ('25 Marquette Point'),
       ('444 Golden Leaf Place'),
       ('31773 Spenser Avenue'),
       ('271 Clemons Hill'),
       ('0 Service Place'),
       ('833 Waxwing Drive'),
       ('32104 Cottonwood Road'),
       ('4736 Monica Point'),
       ('6 Namekagon Court'),
       ('7 Hollow Ridge Hill'),
       ('50 Texas Crossing'),
       ('49099 Manitowish Court'),
       ('49 Parkside Way'),
       ('000 Tomscot Lane'),
       ('74 Main Road'),
       ('260 Sullivan Hill');

insert into addresses (`name`)
values ('6422 Kenwood Street'),
       ('263 Glendale Lane'),
       ('781 Luster Junction'),
       ('1 Express Parkway'),
       ('42 Eggendart Trail'),
       ('3569 Canary Lane'),
       ('713 Brown Point'),
       ('253 Carpenter Plaza'),
       ('78859 Mifflin Place'),
       ('0 Arkansas Center'),
       ('8868 Arkansas Parkway'),
       ('29 Dunning Avenue'),
       ('5 New Castle Terrace'),
       ('411 Pankratz Court'),
       ('75 Harper Way'),
       ('118 Nelson Plaza'),
       ('42 Del Sol Court'),
       ('80315 Sherman Lane'),
       ('2 Bluejay Parkway'),
       ('33901 Pond Circle'),
       ('3 Homewood Circle'),
       ('6776 Village Green Court'),
       ('8 Kinsman Avenue'),
       ('575 Homewood Alley'),
       ('0938 Vermont Junction'),
       ('03632 Carey Trail'),
       ('0922 Stang Circle'),
       ('1930 Quincy Trail'),
       ('432 Elka Hill'),
       ('2 Spaight Alley'),
       ('4442 Heffernan Drive'),
       ('53533 Novick Pass'),
       ('50 Mesta Road'),
       ('90 Summer Ridge Lane'),
       ('241 Burning Wood Plaza'),
       ('6507 Burrows Way'),
       ('5 8th Avenue'),
       ('2 Brown Drive'),
       ('92 Memorial Park'),
       ('036 Stuart Pass'),
       ('13 Maryland Road'),
       ('10 Jenna Park'),
       ('33097 Rieder Pass'),
       ('31314 Butterfield Lane'),
       ('78 Hollow Ridge Junction'),
       ('008 Heffernan Center'),
       ('9 Marcy Court'),
       ('121 Miller Junction'),
       ('906 Buhler Hill'),
       ('6 Evergreen Way'),
       ('86530 Dovetail Park'),
       ('31 Bartillon Way'),
       ('88229 Norway Maple Court'),
       ('5 Sunbrook Point'),
       ('5667 Brentwood Alley'),
       ('887 Rieder Way'),
       ('9324 Shopko Alley'),
       ('699 Alpine Alley'),
       ('29 Beilfuss Center'),
       ('801 Brickson Park Avenue'),
       ('811 Maywood Parkway'),
       ('415 2nd Center'),
       ('46688 Sherman Park'),
       ('60044 Bayside Pass'),
       ('43 Schurz Park'),
       ('20605 Helena Lane'),
       ('9 Mesta Lane'),
       ('5 Homewood Trail'),
       ('33 Prentice Junction'),
       ('51 Algoma Crossing'),
       ('22058 Northland Trail'),
       ('6751 Village Place'),
       ('67 Twin Pines Center'),
       ('1 School Court'),
       ('3696 Elmside Lane'),
       ('22 Riverside Drive'),
       ('1018 Manufacturers Court'),
       ('937 Montana Plaza'),
       ('266 Dayton Street'),
       ('1 West Center'),
       ('8887 Artisan Pass'),
       ('9131 Everett Alley'),
       ('1 Nancy Trail'),
       ('04 La Follette Pass'),
       ('25 Marquette Point'),
       ('444 Golden Leaf Place'),
       ('31773 Spenser Avenue'),
       ('271 Clemons Hill'),
       ('0 Service Place'),
       ('833 Waxwing Drive'),
       ('32104 Cottonwood Road'),
       ('4736 Monica Point'),
       ('6 Namekagon Court'),
       ('7 Hollow Ridge Hill'),
       ('50 Texas Crossing'),
       ('49099 Manitowish Court'),
       ('49 Parkside Way'),
       ('000 Tomscot Lane'),
       ('74 Main Road'),
       ('260 Sullivan Hill');

insert into offices (workspace_capacity, website, address_id)
values (12, 'https://noaa.com', 1),
       (13, 'https://123-reg.co.uk', 72),
       (11, 'http://barnesandnoble.com', 96),
       (3, 'https://dyndns.org', 85),
       (6, 'https://rambler.ru', 53),
       (13, NULL, 90),
       (8, 'http://rakuten.co.jp', 51),
       (4, 'https://icq.com', 16),
       (12, 'https://csmonitor.com', 22),
       (12, 'http://fotki.com', 2),
       (18, 'http://sourceforge.net', 42),
       (7, 'https://narod.ru', 100),
       (16, 'https://engadget.com', 43),
       (20, 'http://marriott.com', 70),
       (13, 'https://squarespace.com', 52),
       (10, 'http://salon.com', 38),
       (15, 'https://home.pl', 53),
       (7, 'https://narod.ru', 76),
       (17, 'http://java.com', 36),
       (1, 'https://amazon.com', 52),
       (15, 'https://issuu.com', 51),
       (7, 'https://google.co.jp', 44),
       (13, 'http://yale.edu', 93),
       (7, NULL, 80),
       (11, 'https://china.com.cn', 93),
       (3, 'https://ucla.edu', 98),
       (14, 'https://mail.ru', 50),
       (9, 'http://time.com', 10),
       (5, 'http://jugem.jp', 72),
       (2, NULL, 34),
       (13, 'http://mediafire.com', 53),
       (5, 'http://cbsnews.com', 27),
       (3, 'https://ebay.com', 75),
       (9, 'https://msu.edu', 39),
       (16, 'http://woothemes.com', 96),
       (19, NULL, 96),
       (20, 'http://wunderground.com', 29),
       (7, 'http://google.com.hk', 96),
       (12, 'http://un.org', 70),
       (2, 'http://hc360.com', 11),
       (18, 'https://microsoft.com', 70),
       (11, 'https://dell.com', 4),
       (5, 'https://nbcnews.com', 21),
       (16, 'https://smugmug.com', 78),
       (4, NULL, 38),
       (12, 'https://google.nl', 74),
       (5, 'https://disqus.com', 7),
       (17, 'http://ucoz.com', 54),
       (5, 'http://alibaba.com', 5),
       (6, 'http://so-net.ne.jp', 87),
       (16, 'https://yolasite.com', 14),
       (17, 'https://list-manage.com', 75),
       (7, 'http://miibeian.com.cn', 63),
       (2, 'http://prnewswire.com', 34),
       (8, 'http://google.es', 5),
       (7, 'http://themeforest.net', 65),
       (20, 'https://census.com', 61),
       (7, NULL, 81),
       (9, 'https://google.com.hk', 35),
       (10, 'https://telegraph.co.uk', 86),
       (13, 'https://edublogs.org', 25),
       (16, 'http://addthis.com', 16),
       (19, 'https://sogou.com', 18),
       (11, 'https://hc360.com', 13),
       (5, 'http://bing.com', 2),
       (1, 'http://economist.com', 15),
       (17, NULL, 74),
       (4, 'https://google.com.br', 30),
       (20, 'http://ca.com', 62),
       (15, 'https://aboutads.info', 55),
       (6, 'https://networksolutions.com', 36),
       (11, 'https://arstechnica.com', 72),
       (2, 'http://vimeo.com', 32),
       (20, 'https://last.fm', 13),
       (19, 'http://squidoo.com', 84),
       (4, 'http://1und1.de', 45),
       (4, 'http://thetimes.co.uk', 69),
       (4, 'https://rediff.com', 6),
       (18, 'https://nyu.edu', 86),
       (6, 'http://cbslocal.com', 45),
       (6, 'http://who.int', 68),
       (20, 'http://miibeian.com.cn', 95),
       (20, 'https://ucoz.ru', 92),
       (3, NULL, 54),
       (18, 'https://state.tx.us', 69),
       (6, 'http://ucoz.ru', 23),
       (20, 'http://pcworld.com', 82),
       (4, 'https://tmall.com', 96),
       (7, 'http://friendfeed.com', 96),
       (16, 'https://bandcamp.com', 32),
       (2, 'http://opensource.org', 66),
       (14, 'http://xrea.com', 97),
       (11, 'http://ftc.com', 40),
       (1, 'https://virginia.edu', 29),
       (15, 'http://github.io', 88),
       (6, NULL, 35),
       (5, 'https://businessinsider.com', 42),
       (10, 'https://chicagotribune.com', 74),
       (9, 'http://engadget.com', 40),
       (19, 'https://ted.com', 2);
